import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import { AuthProvider, useAuth } from '../context/AuthContext';
import { NotificationProvider } from '../context/NotificationContext';
import Toast from '../components/Toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Sidebar() {
  const { user, isAdmin } = useAuth();
  return (
    <aside className="w-64 bg-gray-900 text-white flex flex-col p-4 min-h-screen">
      <div className="text-2xl font-bold mb-8">Crypto Invest</div>
      <nav className="flex flex-col gap-4">
        <Link href="/dashboard" className="hover:text-blue-400">Dashboard</Link>
        <Link href="/profile" className="hover:text-blue-400">Profile</Link>
        <Link href="/copy-trading" className="hover:text-blue-400">Copy Trading</Link>
        {isAdmin && <Link href="/admin" className="hover:text-blue-400">Admin</Link>}
      </nav>
    </aside>
  );
}

function Navbar() {
  const { user, logout } = useAuth();
  return (
    <header className="flex justify-between items-center mb-8">
      <div className="text-xl font-semibold">Crypto & Forex Investment Platform</div>
      <nav className="flex gap-4 items-center">
        {user ? (
          <>
            <span className="text-gray-700">{user.name}</span>
            <button onClick={logout} className="bg-red-500 text-white px-3 py-1 rounded">Logout</button>
          </>
        ) : (
          <>
            <Link href="/login" className="text-gray-700 hover:text-blue-600">Login</Link>
            <Link href="/register" className="text-gray-700 hover:text-blue-600">Register</Link>
          </>
        )}
      </nav>
    </header>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <NotificationProvider>
            <Toast />
            <div className="flex min-h-screen">
              <Sidebar />
              <main className="flex-1 bg-gray-50 p-8">
                <Navbar />
                {children}
              </main>
            </div>
          </NotificationProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
